import {
	pgTable,
	uuid,
	text,
	integer,
	jsonb,
	timestamp,
	index,
} from "drizzle-orm/pg-core";
import { venue } from "./venue.js";
import { customer } from "./customer.js";
import { room } from "./room.js";

export const TENANCY_KINDS = ["private_rental", "scheduled_recurring"];
export const TENANCY_STATUSES = ["active", "paused", "ended"];

/**
 * A tenancy is an ongoing room-use relationship with a customer - a
 * subscription rather than a one-off booking. Two flavours:
 *
 *   `private_rental` - a private (non-public) room is exclusively this
 *   customer's. Flat `monthly_rate_cents`, no calendar entries (the room
 *   is just theirs), one invoice per month.
 *
 *   `scheduled_recurring` - a public room is reserved on a repeating
 *   weekly pattern (e.g. Wed + Thu mornings). The materialiser generates
 *   one `tenancy_session` per occurrence; sessions block the calendar
 *   like booking_segments do. Invoice each month = sum of non-cancelled
 *   sessions in that month at `per_session_rate_cents`.
 *
 * Open-ended by default - set `ends_on` to wind down.
 */
export const tenancy = pgTable(
	"tenancy",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		venue_id: uuid("venue_id").notNull().references(() => venue.id, { onDelete: "cascade" }),
		customer_id: uuid("customer_id").notNull().references(() => customer.id, { onDelete: "restrict" }),
		room_id: uuid("room_id").notNull().references(() => room.id, { onDelete: "restrict" }),

		kind: text("kind").notNull(),
		status: text("status").notNull().default("active"),

		label: text("label"), // optional human label e.g. "Sarah's pottery studio"
		starts_on: text("starts_on").notNull(), // YYYY-MM-DD
		ends_on: text("ends_on"), // YYYY-MM-DD, nullable = open-ended

		invoice_day_of_month: integer("invoice_day_of_month").default(1).notNull(),

		// private_rental
		monthly_rate_cents: integer("monthly_rate_cents"),

		// scheduled_recurring
		// e.g. { by_weekday: ["WE","TH"], time_start: "09:00", time_end: "13:00",
		//        booking_type_id: "...", layout_id: "..." }
		schedule_rule: jsonb("schedule_rule"),
		per_session_rate_cents: integer("per_session_rate_cents"),

		notes: text("notes"),

		createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(() => new Date()).notNull(),
		deletedAt: timestamp("deleted_at", { withTimezone: true }),
	},
	(t) => [
		index("tenancy_venue_status_idx").on(t.venue_id, t.status),
		index("tenancy_customer_idx").on(t.customer_id),
		index("tenancy_room_idx").on(t.room_id),
	],
);

export const TENANCY_SESSION_STATUSES = ["scheduled", "cancelled", "completed"];

/**
 * One occurrence of a scheduled_recurring tenancy. Materialised by the
 * daily cron a few months ahead so the calendar can see future
 * occurrences. Cancel a single session (status = cancelled) to skip a
 * week without affecting the rest of the series.
 */
export const tenancy_session = pgTable(
	"tenancy_session",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		tenancy_id: uuid("tenancy_id").notNull().references(() => tenancy.id, { onDelete: "cascade" }),

		starts_at: timestamp("starts_at", { withTimezone: true }).notNull(),
		ends_at: timestamp("ends_at", { withTimezone: true }).notNull(),

		status: text("status").notNull().default("scheduled"),

		// Snapshot of the tenancy's per-session rate at the time the session
		// was materialised. Lets us change the headline rate without
		// reprice-ing already-invoiced months.
		rate_cents_snapshot: integer("rate_cents_snapshot"),

		cancelled_at: timestamp("cancelled_at", { withTimezone: true }),
		cancelled_reason: text("cancelled_reason"),

		// Once invoiced, points at the tenancy_invoice that included this
		// session. Read-only after that.
		invoice_id: uuid("invoice_id"),

		createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(() => new Date()).notNull(),
		deletedAt: timestamp("deleted_at", { withTimezone: true }),
	},
	(t) => [
		index("tenancy_session_tenancy_idx").on(t.tenancy_id, t.starts_at),
		index("tenancy_session_window_idx").on(t.starts_at, t.ends_at),
	],
);

export const TENANCY_INVOICE_STATUSES = ["draft", "issued", "paid", "void"];

/**
 * Monthly invoice generated by the daily cron on the tenancy's
 * `invoice_day_of_month`. Reference shape: `TI-YYYY-XXXX`.
 */
export const tenancy_invoice = pgTable(
	"tenancy_invoice",
	{
		id: uuid("id").defaultRandom().primaryKey(),
		tenancy_id: uuid("tenancy_id").notNull().references(() => tenancy.id, { onDelete: "restrict" }),
		venue_id: uuid("venue_id").notNull().references(() => venue.id, { onDelete: "cascade" }),
		reference: text("reference").notNull().unique(),

		period_ym: text("period_ym").notNull(), // YYYY-MM

		status: text("status").notNull().default("issued"),

		subtotal_cents: integer("subtotal_cents").default(0).notNull(),
		vat_cents: integer("vat_cents").default(0).notNull(),
		total_cents: integer("total_cents").default(0).notNull(),

		issued_at: timestamp("issued_at", { withTimezone: true }).defaultNow().notNull(),
		paid_at: timestamp("paid_at", { withTimezone: true }),

		notes: text("notes"),

		createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().$onUpdate(() => new Date()).notNull(),
		deletedAt: timestamp("deleted_at", { withTimezone: true }),
	},
	(t) => [
		index("tenancy_invoice_tenancy_period_idx").on(t.tenancy_id, t.period_ym),
		index("tenancy_invoice_venue_status_idx").on(t.venue_id, t.status),
	],
);
